# Generated by Django 3.0.6 on 2020-07-19 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=25)),
                ('segundo_nombre', models.CharField(max_length=25)),
                ('apellido_paterno', models.CharField(max_length=25)),
                ('apellido_materno', models.CharField(max_length=25)),
                ('age', models.PositiveIntegerField(default=1)),
                ('email', models.EmailField(max_length=254)),
                ('rut', models.CharField(max_length=12)),
                ('cargo', models.CharField(choices=[('XX', 'INSERTAR CARGO'), ('XX', 'INSERTAR CARGO')], max_length=2)),
                ('departamento', models.CharField(choices=[('XX', 'INSERTAR DEPARTAMENTO'), ('XX', 'INSERTAR DEPARTAMENTO')], max_length=2)),
                ('sucursal', models.CharField(choices=[('SA', 'Santiago'), ('PR', 'Providencia')], max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
