# Generated by Django 3.0.6 on 2020-07-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dominio_uno',
            field=models.BooleanField(default=False),
        ),
    ]
