from django import forms
from ChartsGAP.models import (
	Dominio
)

dominio_uno = Dominio.objects.get(pk=1)

class AnalisisGAPDominioUnoForm(forms.Form):
	respuesta_uno = forms.BooleanField(label=dominio_uno.seccion.all()[0].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_dos = forms.BooleanField(label=dominio_uno.seccion.all()[0].control.all()[0].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_tres = forms.BooleanField(label=dominio_uno.seccion.all()[0].control.all()[1].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_cuatro = forms.BooleanField(label=dominio_uno.seccion.all()[0].control.all()[1].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_cinco = forms.BooleanField(label=dominio_uno.seccion.all()[0].control.all()[1].subcontrol.all()[2].nombre_subcontrol, required=False, initial=False)
	respuesta_seis = forms.BooleanField(label=dominio_uno.seccion.all()[0].control.all()[1].subcontrol.all()[3].nombre_subcontrol, required=False, initial=False)
	respuesta_siete = forms.BooleanField(label=dominio_uno.seccion.all()[0].control.all()[1].subcontrol.all()[4].nombre_subcontrol, required=False, initial=False)

dominio_dos = Dominio.objects.get(pk=2)

class AnalisisGAPDominioDosForm(forms.Form):
	respuesta_uno = forms.BooleanField(label=dominio_dos.seccion.all()[0].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_dos = forms.BooleanField(label=dominio_dos.seccion.all()[0].control.all()[1].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_tres = forms.BooleanField(label=dominio_dos.seccion.all()[0].control.all()[2].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_cuatro = forms.BooleanField(label=dominio_dos.seccion.all()[0].control.all()[3].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_cinco = forms.BooleanField(label=dominio_dos.seccion.all()[0].control.all()[4].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_seis = forms.BooleanField(label=dominio_dos.seccion.all()[0].control.all()[5].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_siete = forms.BooleanField(label=dominio_dos.seccion.all()[0].control.all()[6].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_ocho = forms.BooleanField(label=dominio_dos.seccion.all()[0].control.all()[7].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_nueve = forms.BooleanField(label=dominio_dos.seccion.all()[1].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_diez = forms.BooleanField(label=dominio_dos.seccion.all()[1].control.all()[1].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_once = forms.BooleanField(label=dominio_dos.seccion.all()[1].control.all()[2].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)

dominio_tres = Dominio.objects.get(pk=3)

class AnalisisGAPDominioTresForm(forms.Form):
	respuesta_uno = forms.BooleanField(label=dominio_tres.seccion.all()[0].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_dos = forms.BooleanField(label=dominio_tres.seccion.all()[0].control.all()[1].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_tres = forms.BooleanField(label=dominio_tres.seccion.all()[0].control.all()[2].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_cuatro = forms.BooleanField(label=dominio_tres.seccion.all()[1].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_cinco = forms.BooleanField(label=dominio_tres.seccion.all()[1].control.all()[1].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)

dominio_cuatro = Dominio.objects.get(pk=4)

class AnalisisGAPDominioCuatroForm(forms.Form):
	respuesta_uno = forms.BooleanField(label=dominio_cuatro.seccion.all()[0].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_dos = forms.BooleanField(label=dominio_cuatro.seccion.all()[0].control.all()[1].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_tres = forms.BooleanField(label=dominio_cuatro.seccion.all()[0].control.all()[2].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_cuatro = forms.BooleanField(label=dominio_cuatro.seccion.all()[0].control.all()[3].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_cinco = forms.BooleanField(label=dominio_cuatro.seccion.all()[1].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_seis = forms.BooleanField(label=dominio_cuatro.seccion.all()[1].control.all()[1].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_siete = forms.BooleanField(label=dominio_cuatro.seccion.all()[1].control.all()[2].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_ocho = forms.BooleanField(label=dominio_cuatro.seccion.all()[2].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_nueve = forms.BooleanField(label=dominio_cuatro.seccion.all()[2].control.all()[1].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_diez = forms.BooleanField(label=dominio_cuatro.seccion.all()[2].control.all()[2].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)

dominio_cinco = Dominio.objects.get(pk=5)

class AnalisisGAPDominioCincoForm(forms.Form):
	respuesta_uno = forms.BooleanField(label=dominio_cinco.seccion.all()[0].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_dos = forms.BooleanField(label=dominio_cinco.seccion.all()[0].control.all()[1].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_tres = forms.BooleanField(label=dominio_cinco.seccion.all()[0].control.all()[2].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_cuatro = forms.BooleanField(label=dominio_cinco.seccion.all()[0].control.all()[3].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_cinco = forms.BooleanField(label=dominio_cinco.seccion.all()[0].control.all()[3].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_seis = forms.BooleanField(label=dominio_cinco.seccion.all()[0].control.all()[4].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_siete = forms.BooleanField(label=dominio_cinco.seccion.all()[0].control.all()[5].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_ocho = forms.BooleanField(label=dominio_cinco.seccion.all()[1].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_nueve = forms.BooleanField(label=dominio_cinco.seccion.all()[1].control.all()[1].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_diez = forms.BooleanField(label=dominio_cinco.seccion.all()[1].control.all()[1].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_once = forms.BooleanField(label=dominio_cinco.seccion.all()[1].control.all()[2].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_doce = forms.BooleanField(label=dominio_cinco.seccion.all()[1].control.all()[2].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_trece = forms.BooleanField(label=dominio_cinco.seccion.all()[1].control.all()[3].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_catorce = forms.BooleanField(label=dominio_cinco.seccion.all()[1].control.all()[3].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_quince = forms.BooleanField(label=dominio_cinco.seccion.all()[1].control.all()[3].subcontrol.all()[2].nombre_subcontrol, required=False, initial=False)
	respuesta_dieciseis = forms.BooleanField(label=dominio_cinco.seccion.all()[1].control.all()[3].subcontrol.all()[3].nombre_subcontrol, required=False, initial=False)
	respuesta_diecisiete = forms.BooleanField(label=dominio_cinco.seccion.all()[1].control.all()[3].subcontrol.all()[4].nombre_subcontrol, required=False, initial=False)
	respuesta_dieciocho = forms.BooleanField(label=dominio_cinco.seccion.all()[1].control.all()[3].subcontrol.all()[5].nombre_subcontrol, required=False, initial=False)
	respuesta_diecinueve = forms.BooleanField(label=dominio_cinco.seccion.all()[1].control.all()[4].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_veinte = forms.BooleanField(label=dominio_cinco.seccion.all()[1].control.all()[4].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_veintiuno = forms.BooleanField(label=dominio_cinco.seccion.all()[1].control.all()[5].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_veintidos = forms.BooleanField(label=dominio_cinco.seccion.all()[1].control.all()[6].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)

dominio_seis = Dominio.objects.get(pk=6)

class AnalisisGAPDominioSeisForm(forms.Form):
	respuesta_uno = forms.BooleanField(label=dominio_seis.seccion.all()[0].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_dos = forms.BooleanField(label=dominio_seis.seccion.all()[0].control.all()[0].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_tres = forms.BooleanField(label=dominio_seis.seccion.all()[0].control.all()[1].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_cuatro = forms.BooleanField(label=dominio_seis.seccion.all()[0].control.all()[1].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_cinco = forms.BooleanField(label=dominio_seis.seccion.all()[0].control.all()[2].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_seis = forms.BooleanField(label=dominio_seis.seccion.all()[0].control.all()[3].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_siete = forms.BooleanField(label=dominio_seis.seccion.all()[1].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_ocho = forms.BooleanField(label=dominio_seis.seccion.all()[1].control.all()[1].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_nueve = forms.BooleanField(label=dominio_seis.seccion.all()[1].control.all()[1].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_diez = forms.BooleanField(label=dominio_seis.seccion.all()[1].control.all()[2].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_once = forms.BooleanField(label=dominio_seis.seccion.all()[2].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_doce = forms.BooleanField(label=dominio_seis.seccion.all()[2].control.all()[1].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_trece = forms.BooleanField(label=dominio_seis.seccion.all()[2].control.all()[1].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_catorce = forms.BooleanField(label=dominio_seis.seccion.all()[3].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_quince = forms.BooleanField(label=dominio_seis.seccion.all()[3].control.all()[1].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_dieciseis = forms.BooleanField(label=dominio_seis.seccion.all()[3].control.all()[1].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_diecisiete = forms.BooleanField(label=dominio_seis.seccion.all()[3].control.all()[1].subcontrol.all()[2].nombre_subcontrol, required=False, initial=False)
	respuesta_dieciocho = forms.BooleanField(label=dominio_seis.seccion.all()[4].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_diecinueve = forms.BooleanField(label=dominio_seis.seccion.all()[4].control.all()[0].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_veinte = forms.BooleanField(label=dominio_seis.seccion.all()[5].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_veintiuno = forms.BooleanField(label=dominio_seis.seccion.all()[5].control.all()[0].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_veintidos = forms.BooleanField(label=dominio_seis.seccion.all()[5].control.all()[1].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_veintitres = forms.BooleanField(label=dominio_seis.seccion.all()[5].control.all()[1].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_veinticuatro = forms.BooleanField(label=dominio_seis.seccion.all()[6].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_veinticinco = forms.BooleanField(label=dominio_seis.seccion.all()[6].control.all()[0].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_veintiseis = forms.BooleanField(label=dominio_seis.seccion.all()[6].control.all()[1].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_veintisiete = forms.BooleanField(label=dominio_seis.seccion.all()[6].control.all()[2].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_veintiocho = forms.BooleanField(label=dominio_seis.seccion.all()[6].control.all()[3].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_veintinueve = forms.BooleanField(label=dominio_seis.seccion.all()[7].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_treinta = forms.BooleanField(label=dominio_seis.seccion.all()[7].control.all()[1].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_treintaiuno = forms.BooleanField(label=dominio_seis.seccion.all()[7].control.all()[1].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_treintaidos = forms.BooleanField(label=dominio_seis.seccion.all()[7].control.all()[2].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_treintaitres = forms.BooleanField(label=dominio_seis.seccion.all()[7].control.all()[3].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_treintaicuatro = forms.BooleanField(label=dominio_seis.seccion.all()[7].control.all()[4].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_treintaicinco = forms.BooleanField(label=dominio_seis.seccion.all()[8].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_treintaiseis = forms.BooleanField(label=dominio_seis.seccion.all()[8].control.all()[0].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_treintaisiete = forms.BooleanField(label=dominio_seis.seccion.all()[8].control.all()[0].subcontrol.all()[2].nombre_subcontrol, required=False, initial=False)
	respuesta_treintaiocho = forms.BooleanField(label=dominio_seis.seccion.all()[8].control.all()[1].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_treintainueve = forms.BooleanField(label=dominio_seis.seccion.all()[8].control.all()[2].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_cuarenta = forms.BooleanField(label=dominio_seis.seccion.all()[9].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_cuarentaiuno = forms.BooleanField(label=dominio_seis.seccion.all()[9].control.all()[1].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_cuarentaidos = forms.BooleanField(label=dominio_seis.seccion.all()[9].control.all()[1].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_cuarentaitres = forms.BooleanField(label=dominio_seis.seccion.all()[9].control.all()[1].subcontrol.all()[2].nombre_subcontrol, required=False, initial=False)
	respuesta_cuarentaicuatro = forms.BooleanField(label=dominio_seis.seccion.all()[9].control.all()[2].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_cuarentaicinco = forms.BooleanField(label=dominio_seis.seccion.all()[9].control.all()[3].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_cuarentaiseis = forms.BooleanField(label=dominio_seis.seccion.all()[9].control.all()[3].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_cuarentaisiete = forms.BooleanField(label=dominio_seis.seccion.all()[9].control.all()[4].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_cuarentaiocho = forms.BooleanField(label=dominio_seis.seccion.all()[9].control.all()[4].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_cuarentainueve = forms.BooleanField(label=dominio_seis.seccion.all()[9].control.all()[5].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)

dominio_siete = Dominio.objects.get(pk=7)

class AnalisisGAPDominioSieteForm(forms.Form):
	respuesta_uno = forms.BooleanField(label=dominio_siete.seccion.all()[0].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_dos = forms.BooleanField(label=dominio_siete.seccion.all()[0].control.all()[0].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_tres = forms.BooleanField(label=dominio_siete.seccion.all()[0].control.all()[0].subcontrol.all()[2].nombre_subcontrol, required=False, initial=False)
	respuesta_cuatro = forms.BooleanField(label=dominio_siete.seccion.all()[1].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_cinco = forms.BooleanField(label=dominio_siete.seccion.all()[1].control.all()[1].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_seis = forms.BooleanField(label=dominio_siete.seccion.all()[1].control.all()[2].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_siete = forms.BooleanField(label=dominio_siete.seccion.all()[1].control.all()[3].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_ocho = forms.BooleanField(label=dominio_siete.seccion.all()[2].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_nueve = forms.BooleanField(label=dominio_siete.seccion.all()[2].control.all()[1].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_diez = forms.BooleanField(label=dominio_siete.seccion.all()[3].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_once = forms.BooleanField(label=dominio_siete.seccion.all()[3].control.all()[0].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_doce = forms.BooleanField(label=dominio_siete.seccion.all()[3].control.all()[1].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_trece = forms.BooleanField(label=dominio_siete.seccion.all()[3].control.all()[2].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_catorce = forms.BooleanField(label=dominio_siete.seccion.all()[3].control.all()[3].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_quince = forms.BooleanField(label=dominio_siete.seccion.all()[3].control.all()[4].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_dieciseis = forms.BooleanField(label=dominio_siete.seccion.all()[3].control.all()[4].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_diecisiete = forms.BooleanField(label=dominio_siete.seccion.all()[3].control.all()[4].subcontrol.all()[2].nombre_subcontrol, required=False, initial=False)
	respuesta_dieciocho = forms.BooleanField(label=dominio_siete.seccion.all()[3].control.all()[5].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_diecinueve = forms.BooleanField(label=dominio_siete.seccion.all()[3].control.all()[6].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_veinte = forms.BooleanField(label=dominio_siete.seccion.all()[3].control.all()[6].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_veintiuno = forms.BooleanField(label=dominio_siete.seccion.all()[4].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_veintidos = forms.BooleanField(label=dominio_siete.seccion.all()[4].control.all()[1].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_veintitres = forms.BooleanField(label=dominio_siete.seccion.all()[4].control.all()[1].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_veinticuatro = forms.BooleanField(label=dominio_siete.seccion.all()[4].control.all()[2].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_veinticinco = forms.BooleanField(label=dominio_siete.seccion.all()[4].control.all()[3].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_veintiseis = forms.BooleanField(label=dominio_siete.seccion.all()[4].control.all()[4].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_veintisiete = forms.BooleanField(label=dominio_siete.seccion.all()[4].control.all()[5].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_veintiocho = forms.BooleanField(label=dominio_siete.seccion.all()[5].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_veintinueve = forms.BooleanField(label=dominio_siete.seccion.all()[5].control.all()[1].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_treinta = forms.BooleanField(label=dominio_siete.seccion.all()[6].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_treintaiuno = forms.BooleanField(label=dominio_siete.seccion.all()[6].control.all()[0].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_treintaidos = forms.BooleanField(label=dominio_siete.seccion.all()[6].control.all()[1].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_treintaitres = forms.BooleanField(label=dominio_siete.seccion.all()[6].control.all()[1].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)

dominio_ocho = Dominio.objects.get(pk=8)

class AnalisisGAPDominioOchoForm(forms.Form):
	respuesta_uno = forms.BooleanField(label=dominio_ocho.seccion.all()[0].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_dos = forms.BooleanField(label=dominio_ocho.seccion.all()[0].control.all()[0].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_tres = forms.BooleanField(label=dominio_ocho.seccion.all()[0].control.all()[0].subcontrol.all()[2].nombre_subcontrol, required=False, initial=False)
	respuesta_cuatro = forms.BooleanField(label=dominio_ocho.seccion.all()[1].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_cinco = forms.BooleanField(label=dominio_ocho.seccion.all()[1].control.all()[0].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_seis = forms.BooleanField(label=dominio_ocho.seccion.all()[1].control.all()[1].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_siete = forms.BooleanField(label=dominio_ocho.seccion.all()[1].control.all()[1].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_ocho = forms.BooleanField(label=dominio_ocho.seccion.all()[1].control.all()[2].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_nueve = forms.BooleanField(label=dominio_ocho.seccion.all()[1].control.all()[2].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_diez = forms.BooleanField(label=dominio_ocho.seccion.all()[1].control.all()[3].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_once = forms.BooleanField(label=dominio_ocho.seccion.all()[2].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_doce = forms.BooleanField(label=dominio_ocho.seccion.all()[2].control.all()[0].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_trece = forms.BooleanField(label=dominio_ocho.seccion.all()[2].control.all()[0].subcontrol.all()[2].nombre_subcontrol, required=False, initial=False)
	respuesta_catorce = forms.BooleanField(label=dominio_ocho.seccion.all()[2].control.all()[1].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_quince = forms.BooleanField(label=dominio_ocho.seccion.all()[2].control.all()[1].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_dieciseis = forms.BooleanField(label=dominio_ocho.seccion.all()[2].control.all()[1].subcontrol.all()[2].nombre_subcontrol, required=False, initial=False)
	respuesta_diecisiete = forms.BooleanField(label=dominio_ocho.seccion.all()[2].control.all()[1].subcontrol.all()[3].nombre_subcontrol, required=False, initial=False)
	respuesta_dieciocho = forms.BooleanField(label=dominio_ocho.seccion.all()[2].control.all()[1].subcontrol.all()[4].nombre_subcontrol, required=False, initial=False)
	respuesta_diecinueve = forms.BooleanField(label=dominio_ocho.seccion.all()[3].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_veinte = forms.BooleanField(label=dominio_ocho.seccion.all()[3].control.all()[1].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_veintiuno = forms.BooleanField(label=dominio_ocho.seccion.all()[3].control.all()[1].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_veintidos = forms.BooleanField(label=dominio_ocho.seccion.all()[3].control.all()[2].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_veintitres = forms.BooleanField(label=dominio_ocho.seccion.all()[4].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_veinticuatro = forms.BooleanField(label=dominio_ocho.seccion.all()[4].control.all()[0].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_veinticinco = forms.BooleanField(label=dominio_ocho.seccion.all()[4].control.all()[1].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_veintiseis = forms.BooleanField(label=dominio_ocho.seccion.all()[4].control.all()[2].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_veintisiete = forms.BooleanField(label=dominio_ocho.seccion.all()[4].control.all()[2].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_veintiocho = forms.BooleanField(label=dominio_ocho.seccion.all()[4].control.all()[3].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_veintinueve = forms.BooleanField(label=dominio_ocho.seccion.all()[4].control.all()[3].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_treinta = forms.BooleanField(label=dominio_ocho.seccion.all()[4].control.all()[4].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_treintaiuno = forms.BooleanField(label=dominio_ocho.seccion.all()[4].control.all()[4].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_treintaidos = forms.BooleanField(label=dominio_ocho.seccion.all()[5].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_treintaitres = forms.BooleanField(label=dominio_ocho.seccion.all()[5].control.all()[0].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)

dominio_nueve = Dominio.objects.get(pk=9)

class AnalisisGAPDominioNueveForm(forms.Form):
	respuesta_uno = forms.BooleanField(label=dominio_nueve.seccion.all()[0].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_dos = forms.BooleanField(label=dominio_nueve.seccion.all()[0].control.all()[0].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_tres = forms.BooleanField(label=dominio_nueve.seccion.all()[0].control.all()[1].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_cuatro = forms.BooleanField(label=dominio_nueve.seccion.all()[1].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_cinco = forms.BooleanField(label=dominio_nueve.seccion.all()[1].control.all()[0].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_seis = forms.BooleanField(label=dominio_nueve.seccion.all()[1].control.all()[0].subcontrol.all()[2].nombre_subcontrol, required=False, initial=False)
	respuesta_siete = forms.BooleanField(label=dominio_nueve.seccion.all()[1].control.all()[1].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_ocho = forms.BooleanField(label=dominio_nueve.seccion.all()[1].control.all()[1].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_nueve = forms.BooleanField(label=dominio_nueve.seccion.all()[1].control.all()[2].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False)
	respuesta_diez = forms.BooleanField(label=dominio_nueve.seccion.all()[1].control.all()[2].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)
	respuesta_once = forms.BooleanField(label=dominio_nueve.seccion.all()[1].control.all()[2].subcontrol.all()[2].nombre_subcontrol, required=False, initial=False)

dominio_diez = Dominio.objects.get(pk=10)

class AnalisisGAPDominioDiezForm(forms.Form):
	respuesta_uno = forms.BooleanField(label=dominio_diez.seccion.all()[0].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False) 
	respuesta_dos = forms.BooleanField(label=dominio_diez.seccion.all()[0].control.all()[0].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False) 
	respuesta_tres = forms.BooleanField(label=dominio_diez.seccion.all()[0].control.all()[1].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False) 
	respuesta_cuatro = forms.BooleanField(label=dominio_diez.seccion.all()[0].control.all()[2].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False) 
	respuesta_cinco = forms.BooleanField(label=dominio_diez.seccion.all()[0].control.all()[2].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False) 
	respuesta_seis = forms.BooleanField(label=dominio_diez.seccion.all()[0].control.all()[3].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False) 
	respuesta_siete = forms.BooleanField(label=dominio_diez.seccion.all()[0].control.all()[3].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False) 
	respuesta_ocho = forms.BooleanField(label=dominio_diez.seccion.all()[0].control.all()[3].subcontrol.all()[2].nombre_subcontrol, required=False, initial=False) 
	respuesta_nueve = forms.BooleanField(label=dominio_diez.seccion.all()[0].control.all()[4].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False) 
	respuesta_diez = forms.BooleanField(label=dominio_diez.seccion.all()[0].control.all()[4].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False)

dominio_once = Dominio.objects.get(pk=11)

class AnalisisGAPDominioOnceForm(forms.Form):
	respuesta_uno = forms.BooleanField(label=dominio_once.seccion.all()[0].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False) 
	respuesta_dos = forms.BooleanField(label=dominio_once.seccion.all()[0].control.all()[0].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False) 
	respuesta_tres = forms.BooleanField(label=dominio_once.seccion.all()[0].control.all()[1].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False) 
	respuesta_cuatro = forms.BooleanField(label=dominio_once.seccion.all()[0].control.all()[1].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False) 
	respuesta_cinco = forms.BooleanField(label=dominio_once.seccion.all()[0].control.all()[1].subcontrol.all()[2].nombre_subcontrol, required=False, initial=False) 
	respuesta_seis = forms.BooleanField(label=dominio_once.seccion.all()[0].control.all()[2].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False) 
	respuesta_siete = forms.BooleanField(label=dominio_once.seccion.all()[0].control.all()[2].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False) 
	respuesta_ocho = forms.BooleanField(label=dominio_once.seccion.all()[0].control.all()[2].subcontrol.all()[2].nombre_subcontrol, required=False, initial=False) 
	respuesta_nueve = forms.BooleanField(label=dominio_once.seccion.all()[0].control.all()[3].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False) 
	respuesta_diez = forms.BooleanField(label=dominio_once.seccion.all()[0].control.all()[4].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False) 
	respuesta_once = forms.BooleanField(label=dominio_once.seccion.all()[0].control.all()[4].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False) 
	respuesta_doce = forms.BooleanField(label=dominio_once.seccion.all()[0].control.all()[4].subcontrol.all()[2].nombre_subcontrol, required=False, initial=False) 
	respuesta_trece = forms.BooleanField(label=dominio_once.seccion.all()[0].control.all()[5].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False) 
	respuesta_catorce = forms.BooleanField(label=dominio_once.seccion.all()[1].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False) 
	respuesta_quince = forms.BooleanField(label=dominio_once.seccion.all()[1].control.all()[0].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False) 
	respuesta_dieciseis = forms.BooleanField(label=dominio_once.seccion.all()[1].control.all()[1].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False) 
	respuesta_diecisiete = forms.BooleanField(label=dominio_once.seccion.all()[1].control.all()[1].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False) 
	respuesta_dieciocho = forms.BooleanField(label=dominio_once.seccion.all()[2].control.all()[0].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False) 
	respuesta_diecinueve = forms.BooleanField(label=dominio_once.seccion.all()[2].control.all()[0].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False) 
	respuesta_veinte = forms.BooleanField(label=dominio_once.seccion.all()[2].control.all()[1].subcontrol.all()[0].nombre_subcontrol, required=False, initial=False) 
	respuesta_veintiuno  = forms.BooleanField(label=dominio_once.seccion.all()[2].control.all()[1].subcontrol.all()[1].nombre_subcontrol, required=False, initial=False) 