# Generated by Django 3.0.6 on 2020-07-19 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Logauth', '0001_initial'),
        ('ChartsGAP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuestados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_encuesta', models.DateTimeField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Logauth.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='dominio',
            name='encuestados',
            field=models.ManyToManyField(blank=True, null=True, to='ChartsGAP.Encuestados'),
        ),
    ]
