# Generated by Django 3.0.6 on 2020-07-20 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChartsGAP', '0002_auto_20200719_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dominio',
            name='encuestados',
        ),
        migrations.DeleteModel(
            name='Encuestados',
        ),
    ]
